language: php

php:
  - 7.1

addons:
  code_climate:
    repo_token: $code_climate_token

before_install: cd backend

install:
  - composer install

after_success:
  - CODECLIMATE_REPO_TOKEN=$code_climate_token vendor/bin/test-reporter